### ISSUE TITLE
More complex examples of builtins

### ISSUE THREAD

**Issue by andreaferretti** [komerdoor/nim-embedded-nimscript#1]
Any idea how to create a builtin that also takes arguments? Or how to expose a compiled function (do we need to go through `scriptRegister` a function of the samename and signature?)

**Comment by komerdoor** [comment]
I did some work on that, but never committed it. Will do it soon.

**Comment by h0lley** [comment]
I'd be interested in that, too.

I haven't been able to find any other repo showcasing the implementation of nimscript as  embedded scripting language, and few are willing or able reverse engineer the nim compiler source to figure all this out.

edit:
For anyone ending up here in the hopes of managing to implement embedded nimscript, I've got you covered: https://github.com/Serenitor/embeddedNimScript
This also lets you call procs with arguments and return values both ways.

**Comment by komerdoor** [comment]
@Serenitor Cool. Had no time to finish this myself. Thanks for helping everyone out.

Can I add a link to your project in the Readme?

**Comment by h0lley** [comment]
sure. I might update it soon.
