### ISSUE TITLE
Error: cannot open 'etcpriv'

### ISSUE THREAD

**Issue by h0lley** [komerdoor/nim-embedded-nimscript#2]
I am getting this error when trying to compile simply with ``nim c main``

Can't find anything about it. Do you have any idea?

I am on win10 with nim 0.17.0

**Comment by h0lley** [comment]
nvm, the issue was that I had outdated sources of the nim compiler

**Comment by deorder** [comment]
Thank you. Note that I am not maintaining this project anymore. You may want to fork it and maintain it from there instead.
